/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: heedongq (https://sketchfab.com/heedongq)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/hearthstone-bar-door-431963f2819a4ad28a19fd3108d7c4a7
Title: Hearthstone bar door
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Hearthstone = (props) => {
  const { nodes, materials } = useGLTF('/models/hearthstone.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.blinn1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.blinn1}
      />
    </group>
  )
}

useGLTF.preload('/models/hearthstone.glb')

export default Hearthstone;

