/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Wieslaw Kruczala (https://sketchfab.com/Wieslaw_Kruczala)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/orbitals-5g0-vs-bohr-model-040dbc6884744e52b6adde01a2e933e8
Title: Orbitals - 5g0 vs Bohr model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Hydrogen = (props) => {
  const { nodes, materials } = useGLTF('/models/hydrogen.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['5G0-10000_0'].geometry}
            material={materials.outermost}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['5G0-10000_0_1'].geometry}
            material={materials.outermost}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['5G0-10000_0_2'].geometry}
            material={materials.outermost}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.proton_0.geometry}
          material={materials.proton}
          scale={0.119}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle_0.geometry}
          material={materials.orbits}
          scale={[0.529, 0.529, 3.145]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Text_0.geometry}
          material={materials.numbers}
          position={[0.174, 0, 0.217]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={1.537}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['5G0-10001_0'].geometry}
          material={materials['Material.001']}
          rotation={[-Math.PI, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['5G0-4_1000_0'].geometry}
          material={materials.inner}
          rotation={[0, 0, -1.602]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/hydrogen.glb')

export default Hydrogen;
